services:
  frontend:
    # image: ollama/ollama:latest
    build:
      dockerfile: frontend/Dockerfile
    command: sleep infinity
    restart: unless-stopped
    # env_file: dev.env
    network_mode: service:backend
    volumes:
      - ..:/workspace:cached
    depends_on:
      - backend

  backend:
    build:
      context: ../
      dockerfile: .devcontainer/backend/Dockerfile
    volumes:
      - ../ollama-data/ollama:/root/.ollama
      - ..:/workspace:cached
    # depends_on:
    #   - ollama
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    command: ollama serve
    environment:
      - OLLAMA_BASE_URLS=http://localhost:11434
      - CORS_ALLOW_ORIGIN=http://localhost:5173;http://localhost:8080
      # - OLLAMA_HOST=127.0.0.1
      # - OLLAMA_BASE_URLS=http://host.docker.internal:11434
      - OLLAMA_KEEP_ALIVE=24h
      - ENV=dev
      - WEBUI_AUTH=False
      - WEBUI_NAME=valiantlynx AI
      - WEBUI_URL=http://localhost:8080
      - WEBUI_SECRET_KEY=t0p-s3cr3t
    # networks:
    #   - ollama-docker
    # # Uncomment to use gpu
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [ gpu ]

#   ollama:
#     volumes:
#       - ../ollama-data/ollama:/root/.ollama
#     # container_name: ollama
#     pull_policy: always
#     tty: true
#     restart: unless-stopped
#     image: ollama/ollama:latest
#     ports:
#       - 11434:11434
#     environment:
#       - OLLAMA_KEEP_ALIVE=24h
#     networks:
#       - ollama-docker

# networks:
#   ollama-docker:
#     external: false